### ISSUE TITLE
Doesn't support the latest version of tshock

### ISSUE THREAD

**Issue by xavierlvll** [xNarnia/TCR-TerrariaChatRelay#36]
Tshock log.
[12/05/22 13:19:13] [Server API] Verbose: TerrariaApi - Server v2.1.0.0 started.
[12/05/22 13:19:13] [Server API] Verbose: 	Command line: C:\Users\Xavie\Desktop\TShock-5.1.3-for-Terraria-1.4.4.9-win-x64-Release\TShock.Server.exe -ignoreversion -disableannouncementbox
[12/05/22 13:19:13] [Server API] Verbose: 	OS: Microsoft Windows NT 10.0.19044.0 (64bit: True)
[12/05/22 13:19:13] [Server API] Verbose: 	Mono: False
[12/05/22 13:19:13] [Server API] Warning: Plugin versions are no longer being regarded, you are on your own! If problems arise, TShock developers will not help you with issues regarding this.
[12/05/22 13:19:14] [Server API] Info: Plugin TShock v5.1.3.0 (by The TShock Team) initiated.
[12/05/22 13:19:14] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TerrariaChatRelay" has thrown an exception during initialization.
 ---> System.TypeLoadException: Could not load type 'Game' from assembly 'OTAPI, Version=1.4.4.9, Culture=neutral, PublicKeyToken=null'.
   at TerrariaChatRelay.TerrariaChatRelay.Initialize()
   at TerrariaApi.Server.PluginContainer.Initialize() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/PluginContainer.cs:line 36
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 430
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 435
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 118
   at TerrariaApi.Server.HookManager.InitialiseAPI() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HookManager.cs:line 29

**Comment by xNarnia** [comment]
A beta version is out for TShock on Windows/Linux and TML Windows on the discord. Once we get TML Linux figured out, a full release will happen. (Hopefully soon!)

**Comment by xNarnia** [comment]
User tested in Discord and runs successfully

**Comment by xavierlvll** [comment]
Works beautifully! thanks for the help!
