### ISSUE TITLE
broken on latest tmodloader version

### ISSUE THREAD

**Issue by jtwebhomer** [xNarnia/TCR-TerrariaChatRelay#43]
[16:10:15.461] [.NET TP Worker/ERROR] [tML]: An error occurred while loading TerrariaChatRelay v2.0.1.5
It has been detected that this mod was built for tModLoader v2024.4.3.2
However, you are using tModLoader v2024.5.3.3
The mod(s) and any dependencies have been automatically disabled.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jtweb\Documents\My Games\Terraria\tModLoader\Mod Configs\TerrariaChatRelay\TerrariaChatRelay-Discord.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at TerrariaChatRelay.TerrariaChatRelay.Load() in TerrariaChatRelay.cs:line 38
   at Terraria.ModLoader.ModContent.<>c.<Load>b__44_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 304
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 408
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 298
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 132
[16:10:41.033] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs"

**Comment by McSquizzleswag** [comment]
This is still very much a thing, I'd love to use this mod instead of the thing I currently have, which is just a webhook

**Comment by xNarnia** [comment]
Hey @McSquizzleswag @jtwebhomer! There have been some big pushes to increase stability in the latest 2025 release. Please let me know if you're still struggling with this!
