### ISSUE TITLE
Error on startup after TShock update (v4.5.5).

### ISSUE THREAD

**Issue by Kojirremer** [xNarnia/TCR-TerrariaChatRelay#8]
Something in the update apparently broke the plugin. After updating to the [most recent TShock release](https://github.com/Pryaxis/TShock/releases/tag/v4.5.5), when I try to start up the server I get this error on boot:

``` [Server API] Error Startup aborted due to an exception in the Server API initialization:

System.InvalidOperationException: Plugin "TerrariaChatRelay" has thrown an exception during initialization. ---> System.TypeLoadException: Could not resolve type with token 0100003b

at TerrariaApi.Server.PluginContainer.Initialize () [0x00006] in <eb79985e9eb3438a965ff73328906b32>:0

at TerrariaApi.Server.ServerApi.LoadPlugins () [0x002eb] in <eb79985e9eb3438a965ff73328906b32>:0

--- End of inner exception stack trace ---

at TerrariaApi.Server.ServerApi.LoadPlugins () [0x00313] in <eb79985e9eb3438a965ff73328906b32>:0

at TerrariaApi.Server.ServerApi.Initialize (System.String[] commandLineArgs, Terraria.Main game) [0x0011a] in <eb79985e9eb3438a965ff73328906b32>:0

at TerrariaApi.Server.HookManager.InitialiseAPI () [0x0004e] in <eb79985e9eb3438a965ff73328906b32>:0

**Comment by wertercatt** [comment]
I can reproduce this error on a fresh install of TShock.
```
[Server API] Error Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TerrariaChatRelay" has thrown an exception during initialization. ---> System.MissingMethodException: Method not found: 'TShockAPI.ConfigFile TShockAPI.ConfigFile.Read(System.String)'.
   at TerrariaChatRelay.TerrariaChatRelay.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 375
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 380
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\ServerApi.cs:line 117
   at TerrariaApi.Server.HookManager.InitialiseAPI() in D:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HookManager.cs:line 27
```

**Comment by xNarnia** [comment]
Thank you for reporting the issue. This issue has been fixed.
https://github.com/xPanini/TCR-TerrariaChatRelay-TShock/releases/tag/0.9.2
